theme: jekyll-theme-cayman
title: Welcome to my website!
description: Here I have blog posts and text based versions of my video tutorials. 
markdown: kramdown

social_links:
    github:  geekjr
    youtube: ARC Academy
    youtube_channel: UC4sMxZHc9HpFufldKBR7DFQ
    youtube_channel_name: ARC Academy
